[package]
name = "neon-class"
version = "0.1.0"
authors = ["nswbmw"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon_class"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.14"

[dependencies]
neon = "0.1.14"

[profile.release]
opt-level = 3